### ISSUE TITLE
Layer specific attribution or scale

### ISSUE THREAD

**Issue by mojoaxel** [aAXEe/online_chart_ol3#27]
Make it possible for layers to have their own copyright-notice, info-button or layer-specific scale.

Example of the OL2 implementation:
![image](https://cloud.githubusercontent.com/assets/600565/13580829/34332b66-e4a4-11e5-9c47-25ef3af89e5b.png)

**Comment by Nautic** [comment]
Die alte Lösung ist nicht benutzerfreundlich: je mehr Daten, desto weniger sieht man von der Karte.

[Generisch mit Link zu Liste im Web ist besser.](http://wiki.openseamap.org/wiki/OpenSeaMap-dev:Fullscreenmap-Layout#Lizenz_und_Quellen)

**Comment by aAXEe** [comment]
I do not think it is a good idea to place all this icons and other stuff in front of the map.
On the other hand some data may require the attribution to show up directly. It is not allowed to place the copyright notices onto another page.

In my opinion it is a good compromise to place layer specific stuff like detailed attributions and keys into the sidebar.

https://github.com/aAXEe/online_chart_ol3/commit/379a696cd3b5ef9c778f2f1889f39485dff4e185 adds the option for each layer to define the necessary map controls while the layer is shown.
This enables the layer not to add additional controls.

This way unnecessary stuff like the scale in nautical units is not shown if no nautical layer is active.

From my point of view this issue is resolved with our system with sidebar and the changes from 379a696cd3b5ef9c778f2f1889f39485dff4e185. What do you think?
