### ISSUE TITLE
Release build does not work in most browsers

### ISSUE THREAD

**Issue by aAXEe** [aAXEe/online_chart_ol3#38]
The output of `npm run production` does not load.

An error message in Chromium: `Uncaught RangeError: Maximum call stack size exceeded`

You can test the current version here: http://dev-map.brasshack.de

**Comment by mojoaxel** [comment]
This is an [UglifyJS issue](https://github.com/mishoo/UglifyJS2/issues/414#issuecomment-208936748).
I disabled source-code compression in production mode for now, until the issue in UglifyJS is solved.

We should not close this issues because the code-compression is very usefull. If the UglifyJS issues doesn't get fixed in near future we should think about using another (gulp-) uglifier insted!

**Comment by mojoaxel** [comment]
I move this to milestone v1.0. 
Nothing to do for now but we should keep out eys on [UglifyJS2](https://github.com/mishoo/UglifyJS2) and update to a newer version of webpack after UglifyJS2@>2.6.2 is released.

**Comment by mojoaxel** [comment]
Also the following packages need to be updated:
* sass-loader 3.1.1 -->  ^3.2.0
* webpack 1.12.4 --> 1.12.15
